[package]
name = "prism"
description = "An experimental chart library for iced."
homepage = "https://github.com/kunerd/prism"
repository = "https://github.com/kunerd/prism"
readme = "README.md"
license-file = "LICENSE"
keywords = ["iced", "chart"]
version = "0.2.1"
edition = "2024"

[dependencies]
ordered-float = "1.0"

[dependencies.iced]
version = "0.14"
default-features = false
features = ["canvas", "advanced", "x11", "thread-pool", "wgpu"]
